### ISSUE TITLE
Column in Excel report to track addins with SourceLink enabled

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#108]

**Comment by gep13** [comment]
@Jericho could you put some details here about what the plan of attack is?

Based on the conversation that I have been having, I think the plan going forward would be to embed a pdb into the nupkg, rather than also publishing a snupkg.  Were you planning on capturing both scenarios?

**Comment by Jericho** [comment]
I intend to replicate the logic in the [SourceLink tool](https://github.com/ctaggart/SourceLink). So far, my understanding of the logic is that it successfully detects if a nuget package contains embedded PDB but I don't think it works if the PDB is in a separate snupkg.

**Comment by Jericho** [comment]
@gep13 here's my plan of attack:

**Phase one:** 
Add a column in Excel report to indicate if PDB is available
- `Green`: PDB is available in NuGet package
- `Yellow`: PDB is available in symbols package
- `Red`: PDB is not available

**Phase two:**
Detect if PDB has been embedded in DLL
- Looking for feedback: what background color should the cell in the Excel report if we determine PDB has been embedded? I'm guessing `Green`.

**Phase three:**
Add a column in Excel report to indicates if SourceLink is enabled
- `Green`: SourceLink is enabled
- `Red`: SourceLink is not enabled

**Comment by Jericho** [comment]
Here's a sneak peak of the PDB column in the Excel report:
![image](https://user-images.githubusercontent.com/112710/89738610-0daa8180-da48-11ea-89a1-89be7b9b6c78.png)

**Comment by Jericho** [comment]
FYI: this is now in production
