### ISSUE TITLE
.NET Core tools referenced using "#tool dotnet:" is not detected

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.AddinDiscoverer#110]
Some time ago, Cake.Recipe added support for using .NET Core tools when building .NET Core projects.
This is done by using `#tool dotnet:` to restore these tools correctly, these references are unfortunately not detected by the AddinDiscoverer, and no issue/pr are ever created when these references have new versions available.

As such, would it be possible to support tools referenced using "dotnet:" also to be detected by the AddinDiscoverer?

**Comment by Jericho** [comment]
Currently we support the following:
- `#addin nuget:`
- `#tool nuget:`
- `#load nuget:`
- `#l nuget:' (`l` is short for `load`)

Should I add support for `#tool dotnet:` only, or `#addin dotnet:` and `#load dotnet:` as well?

**Comment by AdmiringWorm** [comment]
I don't think `#addin dotnet:` and `#load dotnet:` is available to be used.
However, looking at your regex, adding support for all three may perhaps be the easiest instead of just for `#tool dotnet:`, and if so I would say yes 😄

**Comment by Jericho** [comment]
What about `local`? Does Cake.Recipe support it?

**Comment by AdmiringWorm** [comment]
It isn't really a matter of wether Cake.Recipe supports `local` or not (since that is provided by `Cake` itself).

But `Cake.Recipe` do not make use of `local`, so far only `dotnet:` and `nuget:` is being used, there is a possibility that additional module loaders will be used. But so far nothing is planned AFAIK.

**Comment by Jericho** [comment]
FYI: this is now in production
