### ISSUE TITLE
Add type column to excel report

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#115]
It would be nice to have a column in the excel report for the type (addin or module)

**Comment by Jericho** [comment]
Modules are grouped on a separate worksheet in the Excel report

**Comment by pascalberger** [comment]
> Modules are grouped on a separate worksheet in the Excel report

You sure? Looking at https://github.com/cake-contrib/Home/blob/master/Audit.xlsx I've worksheets for different Cake releases (containing addins and modules), Recipes, Exceptions and Deprecated.

**Comment by Jericho** [comment]
you’re right. I was thinking of the sheet for recipes.

**Comment by Jericho** [comment]
Adding new column:
![image](https://user-images.githubusercontent.com/112710/92616032-c0f6d800-f28b-11ea-8674-e0c1317659a7.png)

**Comment by AdmiringWorm** [comment]
@Jericho @pascalberger just a suggestion, maybe this is better to split out to different sheets instead?
Like what is done for recipes?

**Comment by Jericho** [comment]
I'm genuinely curious: why this would be better?

Considering that the information for both addins and modules is exactly the same, I feel having them on the same sheet is better and with @pascalberger suggestion to add a new column to display the type you will be able to easily filter on the desired type.

**Comment by AdmiringWorm** [comment]
It just feels to me that it would make them more distinguishable, although I may be completely wrong in that.
Either way works anyhow.
