### ISSUE TITLE
Exclude Cake.Task plugins

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#117]
@pascalberger I can certainly exclude each of your plugins one by one, but is there some naming convention that they follow and would make exclusion simpler? Something like `Cake.Task.*` or something?

https://github.com/cake-build/website/pull/900
https://github.com/cake-build/website/pull/898
https://github.com/cake-build/website/pull/896
https://github.com/cake-build/website/pull/894
https://github.com/cake-build/website/pull/892

**Comment by gep13** [comment]
@Jericho I think using`Cake.Task.*` is a good idea.

**Comment by Jericho** [comment]
For future reference: anybody can request an addin to be added to the exclusion list by submitting a PR with the proper modification to this file: https://github.com/cake-contrib/Cake.AddinDiscoverer/blob/develop/Source/Cake.AddinDiscoverer/exclusionlist.json

**Comment by Jericho** [comment]
Done. Published in 3.47.0

**Comment by pascalberger** [comment]
@Jericho This doesn't seem to work, since Addin Discoverer just created issues again for the `Cake.Tasks` packages (e.g. https://github.com/cake-build/website/issues/1055)

**Comment by Jericho** [comment]
I excluded Cake.Task.* but your naming convention seems to be Cake.Tasks.* (plural).
