### ISSUE TITLE
Build failing due to GitHub exception: "At least one email address must be verified to do that"

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#137]
For the last 3 days our build has been failing as you can see here: https://ci.appveyor.com/project/cakecontrib/cake-addindiscoverer/builds/36355642#L213

This was reported [here](https://github.com/cake-contrib/Home/issues/68).

**Comment by Jericho** [comment]
@gep13 was able to verify the cake-contrib-bot email address to take care of the first issue:
![image](https://user-images.githubusercontent.com/112710/99718637-2da30580-2a79-11eb-838d-fffdf1035818.png)

Now I discovered a second problem: `Could not find assembly 'netstandard, Version=2.0.0.0`. I'm guessing this is due to the recent;ly updated AppVeyor image which includes net5. I'm investigating...

**Comment by gep13** [comment]
@Jericho as a temporary workaround, just to get things working again, you should be able to use the previous AppVeyor image:

https://www.appveyor.com/docs/build-environment/#image-updates

i.e. set it to `Previous Visual Studio 2019`

**Comment by Jericho** [comment]
@gep13 reverting to the previous appveyor image resolved the problem but it's obviously a temporary solution. I need to find a more permanent solution.

**Comment by gep13** [comment]
Sounds like a plan!
