### ISSUE TITLE
Add a step to validate the GitHub URL

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#14]
After we determine the github URL for the addins, we should add a new step to validate that the URL is the best one.

What I mean by "best" is: use the URL of the github repo under the cake-contrib organization instead of the URL under the original author's account, whenever possible.

This is important because the `Repository` property in several YAML files on the cake web site has not been updated to reflect the fact that some addins were transferred. This causes the audit to incorrectly determine that an addin has not been transferred when in fact it has been

**Comment by Jericho** [comment]
Preliminary result after adding this logic: the audit tool is able to audit 204 addins and 93 are deemed to be transferred to the cake-contrib organization compared to 201 audited addins and 87 deemed to be transferred to the cake-contrib organization with the audit tool currently running in production.

**Comment by gep13** [comment]
Great work!
