### ISSUE TITLE
Output the version of the analyzed NuGet package in YAML

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#143]
Following a Skype call with @pascalberger , we agreed that AddinDisco should output the version of the analyzed NuGet package in the YAML.

The name of the new property will be `AnalyzedPackageVersion`.

**Comment by pascalberger** [comment]
`AnalyzedPackageVersion` is now supported for parsing the YML of the website (it's not implemented yet, that will be done with https://github.com/cake-build/website/issues/1294), but you can go ahead and add the information to the YML files.

**Comment by Jericho** [comment]
Excellent, thank you. I will proceed like we did for `TargetCakeVersion`: create a single issue + PR for the first batch of 75 yaml files, when PR is merge, create the next issue and PR for the next batch, and so on.
