### ISSUE TITLE
Check for alias classes without CakeAliasCategory attribute

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#145]
There are several addins which don't contain `CakeAliasCategory` attribute on the class containing the aliases (see e.g. https://github.com/cake-contrib/Cake.SharePoint/pull/2 for a PR which fixes this). If this addin is missing the aliases won't be listed on the website. It would be nice to have this also checked by addin discoverer.

**Comment by Jericho** [comment]
How about adding a new column to the Excel report to show the categories for each addin? Addins without category attribute would simply have a blank in this new column which would make it easy to spot them.

**Comment by pascalberger** [comment]
> How about adding a new column to the Excel report to show the categories for each addin? Addins without category attribute would simply have a blank in this new column which would make it easy to spot them.

Sounds like a good solution to me

**Comment by Jericho** [comment]
Here are the NuGet packages where the addin assembly does not have any class decorated with the `CakeAliasCategory` attribute:

![image](https://user-images.githubusercontent.com/112710/101987527-8c1b6800-3c62-11eb-8c42-d30a8d92c9f0.png)

They are modules for the most par but, interestingly, Cake.SharePoint is not on this list. I'm assuming your PR was merged and a new version was published with the fix, am I right?

**Comment by pascalberger** [comment]
> They are modules for the most par but, interestingly, Cake.SharePoint is not on this list. I'm assuming your PR was merged and a new version was published with the fix, am I right?

Yes, it has been released yesterday

**Comment by pascalberger** [comment]
> Here are the NuGet packages where the addin assembly does not have any class decorated with the `CakeAliasCategory` attribute:

This doesn't seem to be complete. There are several addins where it is currently missing. [Cake.XmlDocMarkdown](https://github.com/ejball/XmlDocMarkdown/blob/master/src/Cake.XmlDocMarkdown/XmlDocCakeAddin.cs#L14) would be an example.

**Comment by Jericho** [comment]
You're right. I made a typo in a condition which screwed the resulting Excel report. Here's a more accurate list:

![image](https://user-images.githubusercontent.com/112710/101988195-1ca77780-3c66-11eb-89c8-1a3faa865f01.png)
