### ISSUE TITLE
Combine commits/issues/PRs when too many YAML files changed at one time

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#155]
Generally speaking we prefer to create one issue+PR for each modified YAML file which allows independent review, discussion and approval of each one. Typically, only a few are created each day which means that it's manageable and @pascalberger has been very diligently reviewing and merging these PRs so far.

However, when we decide to add new properties to the YAML files, it has the potential of creating more than 200 issues, 200 PR and 200 commits in 200 different branches. That's obviously too much to handle for one person.

I propose that the AddinDiscoverer should combine commits on one single branch, raise one single issue and submit one single PR if the number of modified YAML files is above a certain threshold and I suggest that 25 changed YAML files should be the threshold. I picked this number somewhat arbitrarily but I think it's large enough that it won't interfere with the normal day-to-day operation and at the same time it ensures that nobody has to manually approve more than 200 individual PRs 

Also, as long as this one issue is opened, no further changes to any YAML files will be committed and no new issue/PR should be raised.

**Comment by pascalberger** [comment]
25 seems like a reasonable number to me
