### ISSUE TITLE
Add release date to the generated YAML

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#159]
Date the analyzed package was published to nuget.org

**Comment by Jericho** [comment]
International friendly and human readable format: YYY-MM-DD

I'm not sure if nuget provides hours and minutes, but if I find out that they do I will also make include it (in 24 hours format).

**Comment by Jericho** [comment]
I confirm that I will be able to include hours and minutes. 

FYI: date+time will be in UTC.

**Comment by augustoproiete** [comment]
@Jericho Nice. Given it's date & time and UTC, it might make sense to store them in the ISO 8601-1:2019 standard format (e.g. `2020-12-17T08:13:35.4578436Z`).

```csharp
const string dateStringFormatUtc = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'FFFFFFFZ";
```

This roundtrips well with DateTime correctly setting UTC as the date time kind.
