### ISSUE TITLE
Identify TFM for packages where TFM = `any` or remove it from the metadata

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.AddinDiscoverer#167]
The AddinDiscoverer currently [determines the TFM via the `lib` folder](https://github.com/pascalberger/Cake.AddinDiscoverer/blob/ccf46adecec8e104bdace47c713c7447e5fe5681/Source/Cake.AddinDiscoverer/Steps/AnalyzeNuGetMetadataStep.cs#L55-L57) and at least one package ([Cake.XmlDoc.Checker](https://www.nuget.org/packages/Cake.XmlDoc.Checker/1.0.2)) doesn't have specific folders in the `nupkg` [causing the TFM in the website to be reported as `any`](https://github.com/cake-build/website/blob/c5414f44d6d4669964e6384c8915c66785a9d4b3/extensions/Cake.XmlDoc.Checker.yml#L14-L15).

As of PR https://github.com/cake-build/website/pull/1400, the website will display `any` for "Target Framework", as that's what is in the data, but it's not a real TFM.

I suggest that for cases like this, to derive the TFMs of the Cake.Core or Cake.Common referenced by the addin (Cake.Core taking priority if both references exist).

In this case, [Cake.XmlDoc.Checker ](https://www.nuget.org/packages/Cake.XmlDoc.Checker/1.0.2) currently references [Cake.Core v0.32.1](https://www.nuget.org/packages/Cake.Core/0.32.1), and thus the TFMs would appear as `net46` and `netstandard2.0`.

Alternatively, the TFM could be set as empty and the "Target Frameworks" section on the website would be hidden in cases like this one.

**Comment by pascalberger** [comment]
I don't think implementing additional logic to Addin Discoverer is worth the effort (since this is basically an error in the addin, effort is better spend in fixing the addin). We can easily filter the `any` target in website code and mention that we couldn't detect target framework for this specific addin.

**Comment by augustoproiete** [comment]
Agreed it's an issue with this add-in in particular, but can happen with other add-ins in the future, so it makes sense to handle `any` - either in the website or in the Addin Discoverer.

The addin maintainer doesn't seem to be active in the last couple of years. There's an [old issue from @Jericho](https://github.com/dotnetaddicted/cake-xmldoc-checker/issues/1) with best practices recommendations that didn't get acted on nor acknowledged, so I'm skeptical there's interest from the maintainer to fix the nupkg

I'm not against handling it in the website, but similar to the `Isprerelease`, I think it would be cleaner to fix the problem at the source (metadata). Ultimately `any` is not a valid value for `TargetFrameworks` thus I'd suggest handling it in AddIn Discoverer the same way as #168, and write an empty array in the YAML so that the metadata is correct. (happy to send a PR to AddinDisco if we go this route, @Jericho LMK)

**Comment by Jericho** [comment]
@pascalberger is right: the underlying issue should be fixed in the addins nuget packages but as I have learned over that last few years, it's nearly impossible to get all addin authors to resolve issues even if we submit PRs to address it.

So, it makes sense to add logic in the discoverer to filter out the unknown TFM.
