### ISSUE TITLE
Exclusion list must be case-insensitive

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.AddinDiscoverer#179]
Relates to:
- https://github.com/cake-build/website/pull/1713
- https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/177
- https://github.com/cake-build/website/pull/1331

Looks like the process that filters is case-sensitive. PR #177 excluded Cake.**Aws**.ElasticBeanstalkTools but the package name is Cake.**AWS**.ElasticBeanstalkTools

**Comment by Jericho** [comment]
The intention has always been for the "exclusion" process to be case-insensitive. Thanks for pointing out that it's not working quite as intended.

If you don't mind, I will reject the PR your submitted and ensure the process is case-insensitive. I'd rather do that than adding multiple spellings for each addin in the exclusion list.
