### ISSUE TITLE
Plot a graph to show percentage of addins compatible with a given version of Cake over time

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#18]
AddinDiscoverer should generate a graph (an image such as a `.jpg` would be convenient) that shows the percentage of addins compatible with a given version of Cake such as 0.26.0 and 0.28.0 over time

**Comment by Jericho** [comment]
Resolved in 2.2.0

**Comment by gep13** [comment]
@Jericho this is AWESOME!!!

![image](https://user-images.githubusercontent.com/1271146/41205268-4cb2adb4-6ce8-11e8-9731-dcf2fd66e052.png)

Great work!
