### ISSUE TITLE
Additional column in Excel report to indicate if addin uses Cake.Recipe

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#20]
it would also be great to know what version of it is being used and whether it is a prerelease.

**Comment by gep13** [comment]
@Jericho it isn't a requirement that this is the case.  At best, it is a suggestion, but people can bring their addin's into the Cake-Contrib Organisation, without the need to adopt Cake.Recipe.

**Comment by gep13** [comment]
Yes, that is true.  I have no problem with this information being reported in the Excel file, just don't think it should make it into the automated issue creation yet.

**Comment by Jericho** [comment]
oh I agree, it wouldn't be in issue creation just like 'is transferred to cake-contrib organization' is not part of issue creation either.

**Comment by gep13** [comment]
@Jericho sounds perfect to me then! :+1:

**Comment by Jericho** [comment]
Telltale sign that an addin is using Cake.Recipe: Having a load preprocessor directive in a .cake file with Cake.Recipe as package name would be the sure way to know. There are other indicators as well, but that would be the main one.

**Comment by gep13** [comment]
@Jericho Just wanted to touch base on if you had a rough idea on when this was likely to land.  Very curious to see what % of addins are using Cake.Recipe, and what version they are using.  Thanks

**Comment by Jericho** [comment]
I was just working on it this morning. Added an option to turn it off if desired because it takes so long to complete and was testing that. I also had the idea of adding a summary when done to show how long each step takes (similar to the summary Cake displays when executing a script) but I’ll save that for later. 

Anyway, long story short: I’ll publish update later today when I’m done testing.

**Comment by Jericho** [comment]
Here's a teaser:

![image](https://user-images.githubusercontent.com/112710/62426233-f657ec00-b6af-11e9-8d2a-b322631dff4b.png)

**Comment by gep13** [comment]
@Jericho that is great news! I like the idea of being able to turn it on and off as required, and the overall summary also is a great addition!

**Comment by gep13** [comment]
That screenshot looks amazing, and will really help to focus attention on which addins to help update!

**Comment by Jericho** [comment]
That's a pivot table I manually created based on the data produced by AddinDiscoverer.

**Comment by gep13** [comment]
Understood. The fact that all of that data is available is the main thing! This is amazing!

**Comment by Jericho** [comment]
Version 3.25.0 is being published
