### ISSUE TITLE
Add initial Cake.TestModules to exclusion list

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.AddinDiscoverer#203]
The modules below will be published to nuget.org soon and are not intended to be in the website - they are dummy packages for testings modules that target different TFMs against different versions of the Cake runner

- `Cake.TestNet461.Module`
- `Cake.TestNet50.Module`
- `Cake.TestNet60.Module`
- `Cake.TestNetCoreApp31.Module`
- `Cake.TestNetStandard20.Module`
- `Cake.TestNetStandard21.Module`

**Comment by Jericho** [comment]
Cake.AddinDiscoverer 3.78.0 is being published as I type this. The 6 packages you added to the exclusion list will be ignored from now on.

Thank you for your contribution.

**Comment by Jericho** [comment]
By the way, future changes to exclusion list will be effective as soon as the PR is merged. There will be no need to publish a new version of the discoverer. See #205.

**Comment by augustoproiete** [comment]
> By the way, future changes to exclusion list will be effective as soon as the PR is merged. There will be no need to publish a new version of the discoverer. See #205.

This is great! :tada:
