### ISSUE TITLE
Excel report should identify which recipes include cake-version.yml

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#211]
As a result of a recent discussion between @gep13, @pascalberger and myself, we will add a new "best practice" rule for recipes: they should include a file called `cake-version.yml` which should include the version of Cake they target and the .NET framework(s) they are compatible with.

The "Recipes" worksheet in the Excel report generated by Addin Discoverer should have a new column to indicate if the file is present and contains the expected data.

**Comment by pascalberger** [comment]
The cake-version.yml file will only be available for recipes for Cake scripting. For recipes targeting Cake Frosting you can read version from the csproj

**Comment by Jericho** [comment]
![image](https://user-images.githubusercontent.com/112710/190917199-62221686-7b7c-4e1e-88ab-b91c1b127a0f.png)
