### ISSUE TITLE
Exclude contributors from forked repositories

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#224]
The [bitrise-steplib repository](https://github.com/cake-build/bitrise-steplib) is forked. Since upstream contributors did not directly contribute to Cake, we should exclude contributors to this (or any other forked repository) to the list of contributors.

**Comment by Jericho** [comment]
We currently exclude private repos. I will add another criteria to also exclude forks.

**Comment by Jericho** [comment]
There are more than 50 contributors associated with the forked repo. This means that more than 50 names will be removed from the generated YAML and JSON documents when this improvement is published.
