### ISSUE TITLE
Add blacklist for contributors

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#226]
We should implement a blacklist to filter out bots from contributors list.

Some bots I found:

- [allcontributors[bot]](https://github.com/apps/allcontributors)
- [cake-contrib-bot](https://github.com/cake-contrib-bot)
- [codetriage-readme-bot](https://github.com/codetriage-readme-bot)
- [dependabot-preview[bot]](https://github.com/apps/dependabot-preview)
- [dependabot-support](https://github.com/dependabot-support)
- [dependabot[bot]](https://github.com/apps/dependabot)
- [github-actions[bot]](https://github.com/apps/github-actions)
- [gitter-badger](https://github.com/gitter-badger)
- [mergify[bot]](https://github.com/apps/mergify)
- [renovate-bot](https://github.com/renovate-bot)
- [renovate[bot]](https://github.com/apps/renovate)

**Comment by Jericho** [comment]
I just noticed that GitHub users (as returned from the GitHub API) have a property called "Type" which contains either the string `User` or `Bot` as you can see in this screenshot:

![image](https://github.com/cake-contrib/Cake.AddinDiscoverer/assets/112710/e018555d-0daa-4c6b-821c-e9164c301a76)

I could automatically filter out all bots based on the content of this "Type" property rather than manually maintain an exclusion list.

**Comment by pascalberger** [comment]
Would definitely make sense to filter based on available metadata. Not sure though if this catches all bots. I would expect for example `cake-contrib-bot` to be marked as user. For these cases we still can maintain a manual blacklist

**Comment by Jericho** [comment]
Publishing a new version of AddinDisco that automatically filters based on the "Type" property and also introduces an exclusion list: 

https://github.com/cake-contrib/Cake.AddinDiscoverer/blob/develop/Source/Cake.AddinDiscoverer/exclusionlist.json#L74-L75

**Comment by Jericho** [comment]
AddinDisco was able to filter out 6 bots based on the GitHub user metadata in the [latest PR](https://github.com/cake-build/website/pull/2714).

Specifically:
- allcontributors[bot]
- dependabot-preview[bot]
- dependabot[bot]
- github-actions[bot]
- mergify[bot]
- renovate[bot]

but it did not detect the other 5 that you had listed:
- cake-contrib-bot
- codetriage-readme-bot
- dependabot-support
- gitter-badger
- renovate-bot

@pascalberger Please accept the current PR and close the associated issue. In the mean time I will manually add these 5 to the exclusion list. When this is all done, AddinDisco will submit a new PR to remove the 5 excluded GitHub users..

**Comment by pascalberger** [comment]
@Jericho PR for website has been merged

**Comment by Jericho** [comment]
ok thanks. Triggering a new build of AddindDisco, we should get a PR to remove the excluded contributors in a few minutes

**Comment by Jericho** [comment]
>   Only 145 GitHub API requests left. Therefore skipping contributors files synchronization.

The latest build complete and unfortunately, AddinDisco skipped the contributors file synchronization because we were about to trigger GitHub's abuse detection. I'll launch a new build later today.
