### ISSUE TITLE
Filter out packages that do not contain Cake aliases

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#23]
As [suggested](https://github.com/cake-build/website/issues/540#issuecomment-399939451) by @pascalberger , we should attempt to detect if the chosen DLL in a given nuget package contains Cake aliases. If so, the package is audited and yaml file created/updated. If not, the package is filtered out.

**Comment by Jericho** [comment]
When using reflection to loop through types and their methods in an assembly looking for custom attributes, dependencies must be loaded which leads to errors if the referenced nuget package is not present.

Which leads me to think that I either find a way to download all the dependencies and add them to global nuget cache or I abandon the idea to searching for custom attributes.

**Comment by Jericho** [comment]
@pascalberger would like to sanity check something with you: you currently have a nuget package called Cake.Issues.Testing which is being analyzed by the AddinDiscoverer because it matches the naming convention `Cake.*` and the discoverer is able to successfully determine this addin is referencing the proper version of Cake.Core and Cake.Common, the references are private, this addin is targeting the expected .net framework, the proper icon is embedded in the package, etc.

This is all good. Except, please correct me if I'm wrong, this package does not seem to have any public method decorated with one of Cake's alias attribute. Therefore, if I go forward with the new logic, this nuget package would be deemed to **not** be a proper addin and would be listed on the "Exceptions" tab in the Excel report rather than be analyzed. Do you agree with that?

**Comment by pascalberger** [comment]
@Jericho Yes, Cake.Issues.Testing is not an addin, but a library which can be used to help write tests for Cake.Issues addins.

**Comment by Jericho** [comment]
@pascalberger Excellent. Thank you for confirming.

**Comment by Jericho** [comment]
I'm glad to report that I was able to figure out how to inspect assemblies with reflection and overcome the problems I experienced related to missing dependencies. This means I will be able properly reject NuGet packages that do not contain methods decorated with one of Cake's attributes (such as the Cake.Issues.Testing example @pascalberger and I previously discussed).

As a bonus, it also means that I will be able to loop through all assemblies in a given nuget package, inspect each one until I find the one with expected attributes. I no longer need to rely on the DLL following our naming convention. Consequently, it renders the fix for #121 moot.

**Comment by Jericho** [comment]
Here's what the exception tab in the Excel report will look like:

![image](https://user-images.githubusercontent.com/112710/95758213-26b4f600-0c76-11eb-8f47-0735db5f6c0f.png)

I need to investigate what to do about the missing 'FSharp' assembly.

**Comment by Jericho** [comment]
The problem with Cake.GithubUtility turned out to be that this addin was written in FSharp. I was able to resolve it by simply adding a reference to FSharp.Core in AddinDiscoverer's csproj. I'm sure we will have a similar problem if someone published an addin written in VB.NET or other language but I'll deal with that problem if/when we encounter it.

With this problem out of the way, the exception tab in the Excel report looks like this:
![image](https://user-images.githubusercontent.com/112710/95908700-66113e80-0d6b-11eb-8950-3a9e99be43ef.png)

**Comment by Jericho** [comment]
Released in 3.50.0
