### ISSUE TITLE
Unable to commit in cake-build/website repo

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#24]
The cake-contrib-bot is not authorized to commit to the cake-build/website repo, as [confirmed](https://github.com/cake-build/website/issues/540#issuecomment-399951745) by @devlead , which means that we can't delete/create/update yaml files.

We need to add the following logic:
- [x] Create a fork of the cake-build/website repo if a fork doesn't exist
- [x] Make sure the fork is up-to-date with upstream repo
- [x] Create the branch and make commits in the fork
- [x] Submit PR from fork to upstream repo

**Comment by gep13** [comment]
@Jericho I have created a fork here:

https://github.com/cake-contrib/website

**Comment by Jericho** [comment]
@gep13 thanks

**Comment by pascalberger** [comment]
Note that the fork should be updated before creating the branch or the branch should be created from upstreams develop branch

**Comment by Jericho** [comment]
One challenge I'm facing is that Github throws `Octokit.AbuseException: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.` when I try to add and modify a large number of YAML files. This is a problem right now because there are so many files to add and update and probably will not be a problem going forward since there will only be a limited number of yaml files to modify at any given time.

I'm tempted to hard code a max number of files to modify at any time (say 75 files) in order to avoid this problem. When the PR is merged, the audit tool would create another PR for the next 75 files, and so on.

Makes sense?

**Comment by Jericho** [comment]
This issue is resolved in version 3.4.0
