### ISSUE TITLE
Generate YAML for Modules

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#26]
Currently Modules are excluded from YAML generation process because Cake web site cannot handle them.

The `SynchronizeYmlFilesAsync` method filters them out with:
```csharp
    .Where(addin => addin.Type == AddinType.Addin)
```

When Cake's web site is ready, we can change the filter to accept `AddinType.Module` in addition to `AddintType.Addin`.

**Comment by pascalberger** [comment]
@Jericho Website now supports modules and Addin Discoverer can create YAML files for them. Modules should have `Type: Module`

**Comment by Jericho** [comment]
Other the type, everything else is the same?

I'll work on this tomorrow.

**Comment by pascalberger** [comment]
> Other than the type, everything else is the same?

Yes, same metadata as addins
