### ISSUE TITLE
Don't update addins to pre-release versions in Cake.Recipe

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#32]
Pre-release versions of addins should be ignored while updating Cake.Recipe (as done [here](https://github.com/cake-contrib/Cake.Recipe/pull/255/files#diff-4644654b65bb0f0b1c1659e317e9bf1bR20))

**Comment by Jericho** [comment]
Makes sense. I’ll make the improvement.

**Comment by Jericho** [comment]
Version 3.5.0 released
