### ISSUE TITLE
Upgrade 'tool' references in Cake.Recipe

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#34]
As discussed here: https://github.com/cake-contrib/Cake.Recipe/pull/265

**Comment by pascalberger** [comment]
Would definitely be interested in this also for Cake.Issues.Recipe and Cake.Wyam.Recipe

**Comment by gep13** [comment]
I am starting to wonder whether this could be a good addition into dependabot itself, but I am not sure what the criteria is for getting stuff added into there.

**Comment by gep13** [comment]
@Jericho @pascalberger so, I reached out to the people at dependabot, and they said that it would be possible to add a new "language" into their service which would be able to notify users of changes in dependencies.

This work would need to be done in this repo:

https://github.com/dependabot/dependabot-core

And an example PR which added a new language is here:

https://github.com/dependabot/dependabot-core/pull/648

This service is written in Ruby, so it counts me out as I don't know it well enough to start looking at this.  @Jericho is this something that you have experience with?  Would you be interested in taking a stab at this?  I think it would be a great addition, and would let lots of people start to use this on the repositories where they are using Cake.  What are your thoughts?

**Comment by Jericho** [comment]
@gep13 I don’t know Ruby at all so I won’t be able to collaborate with the dependabot project. 

Having said that, I could improve the audit tool to accept a parameter for the name of the repo to scan. Which would mean that all its ‘.cake’ files would be scanned and an issue + PR created whenever a reference needs to be upgraded. Anybody could compile the audit tool and run it from command line with appropriate parameters to scan their own repo.

**Comment by Jericho** [comment]
Two more thing that the audit tool does that probably don’t fit with dependabot (I could be wrong):

- upgrade a given addin reference if and only if the addin version is compatible with the version of Cake used to build the recipe files
- create issue + PR to upgrade the version of Cake used to build the recipe fil when ALL addins references are compatible with a more recent version of Cake

**Comment by Jericho** [comment]
Upgrading "tool" references in addition to "addin" references will be included in the next release

**Comment by Jericho** [comment]
Reopening because it was not working as expected. In fact I had made an incorrect assumption about tool naming that prevented this from working at all.

**Comment by Jericho** [comment]
I fixed my incorrect assumption and ran the audit tool against the current Cake.Recipe and here are the tools that have been identified as outdated: 

![image](https://user-images.githubusercontent.com/112710/48665953-36c1fc00-ea86-11e8-9323-8f4b965daef6.png)

**Comment by Jericho** [comment]
3.8.0 published
