### ISSUE TITLE
Improve commit message for updating addin references

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#36]
It would be nice if the addins which were updated were visible in the commit message.

So instead of ` (GH-123) Update addins references` something like 

```
(GH-123) Update addin references

Cake.Git 1.2.3
Cake.MicrosoftTeams 4.5.6
```

**Comment by pascalberger** [comment]
I know this information is available in the issue, my use case is if I look at the [commit history](https://github.com/cake-contrib/Cake.Recipe/commits/develop), it would be helpful to have this information at hand (I could also just click on the commit to see what has changed, but it's one additional click).

I don't know what the actual limit of Git commit messages are, but it's definitely way higher than you ever will reach with this kind of thing and probably depend on the plattform. The important thing is that you have a short first line (the so-called subject) separated by a blank line. This helps Git clients to show the message correctly (e.g. only the first line, with the remaining part in a tooltip).

**Comment by Jericho** [comment]
I think it makes sense: the history show the same generic commit message over and over without indicating which references were upgraded. I’ll make the improvememt.

**Comment by Jericho** [comment]
Here's what the commit messages will look like:

![image](https://user-images.githubusercontent.com/112710/48665064-5d783680-ea76-11e8-8b96-b2da35a7c11f.png)

Also, I'm noticing that markdown is not respected in commit message so I will remove the unnecessary back-ticks.

**Comment by Jericho** [comment]
3.8.0 published
