### ISSUE TITLE
Add a few additional NuGet packages to blacklist

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#40]
- [x] Cake.Frosting
- ~~Cake.Prompt~~
- [x] Cake.CompressionNetStandard

**Comment by gep13** [comment]
Cake.Frosting I agree should be blacklisted, but Cake.Prompt will likely get pulled in via the open PR that already exists. Is this why it is being blacklisted, since there is already an open PR?

**Comment by Jericho** [comment]
@devlead made a comment about Cake.Prompt in [PR](https://github.com/cake-build/website/pull/630)

**Comment by Jericho** [comment]
Removed Cake.Prompt
Added Cake.CompressionNetStandard

**Comment by Jericho** [comment]
Cake.AddinDiscoverer 3.12.2 released
