### ISSUE TITLE
Check for repository attribute

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AddinDiscoverer#44]
Similar to what was done in this commit:

https://github.com/cake-contrib/Cake.Npm/commit/cbd7291699d3df806e3749d528766981aa4d0b3c

@Jericho thoughts?

**Comment by AdmiringWorm** [comment]
Which would correspond to the following in a csproj file
```xml
<PropertyGroup>
  <RepositoryUrl>https://github.com/cake-contrib/Cake.AddinDiscoverer</RepositoryUrl>
  <RepositoryType>git</RepositoryType>
</PropertyGroup>
```

reference: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

**Comment by Jericho** [comment]
No problem, I’ll add a column to the Excel report.

**Comment by Jericho** [comment]
The weird thing is that I am not seeing the "repo url" in the package metadata:

![image](https://user-images.githubusercontent.com/112710/56505296-4340f980-64e9-11e9-8be0-8a6b1258b2d5.png)

The `projectUrl` is present but I was also expecting something like `repositoryUrl`.

**Comment by Jericho** [comment]
Also I was just thinking: in 99.99% of addins, the repo and the project URL will be the same. I know there are a few addin author who have setup a web site for their addin but in the vast majority of cases the github repo is the project url. 

All this to say, why are we encouraging addin authors to include this info? What's the benefit? Do we intend at some point to point each addin projectUrl to some documentation web site or something?

**Comment by gep13** [comment]
This was a new piece of metadata that was added here:

https://blog.nuget.org/20180827/Introducing-Source-Code-Link-for-NuGet-packages.html

**Comment by Jericho** [comment]
I am aware that's it's a new piece of metadata but my question is: what's the benefit for addin authors? Why are we recommending they should add this info to their nuspec?

**Comment by gep13** [comment]
Fair point.

There is no immediate answer other than "why not" :smile:

It doesn't impact on anything, i.e. there is no downside to doing it.

**Comment by Jericho** [comment]
I was hoping for a better benefit. I don't really feel like getting into debates with addin authors when the answer is simply "why not". It's difficult enough sometimes to get them to accept our recommendations even when there is a clear benefit (for example, I still get push back sometimes regarding which .net framework they should targe and also I have started getting push back regarding the new icon URL), imagine when I am not able to articulate a benefit to them...

**Comment by gep13** [comment]
Yip, that's a fair point.  It might be nice to "collect" that information, i.e. which addins aren't using it, and perhaps not add it as a suggestion, yet?

**Comment by Jericho** [comment]
@gep13 The nuspec accepts not only the repo type and url but also brnach name and commit SHA. Isn't that aslo the information necessary to configure SourceLink/GitLink? If so, is it conceivable that we could define a task in Cake.Recipe to automagically setup this debugging for all addins that provide the necessary repository info?

From [nuspec documentation](https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository):

> Repository metadata, consisting of four optional attributes: type and url (4.0+), and branch and commit (4.6+). These attributes allow you to map the .nupkg to the repository that built it, with the potential to get as detailed as the individual branch or commit that built the package. This should be a publicly available url that can be invoked directly by a version control software. It should not be an html page as this is meant for the computer. For linking to project page, use the projectUrl field, instead.

**Comment by AdmiringWorm** [comment]
I also found out the the url used in the repository url is meant to be the exact url you use when running `git clone` (IE, the link to the repository + `.git`)

:+1: for Cake.Recipe to figure out at least the commit sha (don't think the branch would be necessary when a sha is used).

**Comment by Jericho** [comment]
Column added to the Excel report:

![image](https://user-images.githubusercontent.com/112710/57721404-17311800-7652-11e9-89fb-781ba64b968b.png)

**Comment by gep13** [comment]
@admiringworm I also got confirmation here:

https://twitter.com/adgrv/status/1127591787697061888?s=21

Just to make sure.

**Comment by Jericho** [comment]
Here's a suggestion: instead of simply "red/green" cells in the Excel report we could have a third state (I suggest "yellow") when the repository info is present in the nuspec but `.git` is missing. What do you think?

**Comment by gep13** [comment]
@Jericho sounds great to me!

**Comment by Jericho** [comment]
Here's what it will look like:

![image](https://user-images.githubusercontent.com/112710/57730010-82381a00-7665-11e9-825d-f2cba3e812fa.png)

**Comment by Jericho** [comment]
FYI, as of a few minutes ago, 79 addins have the `repository` info in their nuspec but only 9 include the `.git` extension

**Comment by gep13** [comment]
So a bit of work to be done here as well. Thanks for bringing this to the surface though!

**Comment by Jericho** [comment]
3.15.1 released. You can see the Excel report with the new column [here](https://github.com/cake-contrib/Home/blob/master/Audit.xlsx).
