### ISSUE TITLE
Triggering too many GitHub abuse rate limits

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#47]
I am getting a lot of:
`You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.`

I think I am triggering this even more due to the fact that I am attempting to a lot of PRs. 

The issue is that this gets triggered when fork is created, branch is created, changes committed but PR not created.

**Comment by Jericho** [comment]
I will restrict the number of addins processed in parallel to only one in `SubmitGithubPullRequest`

**Comment by AdmiringWorm** [comment]
Maybe using the [octokit.net.extensions](https://github.com/mirsaeedi/octokit.net.extensions) could be a possibility as well (in addition)?

It have some default policies built in which will be used if no custom policies have been specified.
Two of those policies is related to rate limit, and abuse rate limits.
The policies implemented will retry after a certain amount of time when it hits one of them (the time is based on the returned headers from github).

Just a suggestion.

**Comment by AdmiringWorm** [comment]
Another option could perhaps be by throttling the connections, and making regular checks to see how long it is until the rate limit is reached:
Example of checking the rate limit is here: https://github.com/octokit/octokit.net/blob/master/docs/getting-started.md#too-much-of-a-good-thing-dealing-with-api-rate-limits

**Comment by Jericho** [comment]
I don't think a "retry" policy would help: if I trigger their rate limit I may have to wait something like 45 minutes to retry.

Having said that, I really like your second suggestion. I already throttle to 10 concurrent connections but I should enhance my logic to safely abort if the number of remaining calls is below a certain threshold.

**Comment by Jericho** [comment]
by the way my current workaround to limit to only a single connection works fine altough it takes much longer to go through and process all addins.

**Comment by AdmiringWorm** [comment]
> I don't think a "retry" policy would help: if I trigger their rate limit I may have to wait something like 45 minutes to retry.

It could, from my understanding, the `Retry-After` header can be just a few seconds at times (30 seconds is shown an githubs best practices page, of course that is just an example and may vary).

THe same page recommends to use the api in serial, and not concurrently, it also mentions to wait at least 1 second between requests using `POST`, `PATCH`, `PUT`, or `DELETE`.
ref: https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits

**Comment by Jericho** [comment]
Concurrency was a very deliberate choice to process 200+ addins much faster and it has served us well in the last year or so. However, in this specific case it triggered their abuse detection because we make several calls for each addin: fork the repo, creae a branch, make a few commits, submit PR.

Also, the suggestion to add a 1 second delay here and there makes sense.

**Comment by Jericho** [comment]
I think one of the main reasons I get flagged for abuse it that I searching each repo for files with `.nuspec` and `.csproj` extensions like so:
```
var extensions = new[] { ".csproj", ".nuspec" };
var files = await GetFilesFromRepoAsync(context, addin, extensions, null).ConfigureAwait(false);
```

```
private async Task<RepositoryContent[]> GetFilesFromRepoAsync(DiscoveryContext context, AddinMetadata addin, IEnumerable<string> extensions, string folderName = null)
{
	var files = new List<RepositoryContent>();

	var directoryContent = string.IsNullOrEmpty(folderName) ?
			await context.GithubClient.Repository.Content.GetAllContents(addin.GithubRepoOwner, addin.GithubRepoName).ConfigureAwait(false) :
			await context.GithubClient.Repository.Content.GetAllContents(addin.GithubRepoOwner, addin.GithubRepoName, folderName).ConfigureAwait(false);

	var filesInRoot = directoryContent.Where(c => c.Type == new StringEnum<ContentType>(ContentType.File) && extensions.Contains(System.IO.Path.GetExtension(c.Name), StringComparer.OrdinalIgnoreCase));
	files.AddRange(filesInRoot);

	var subFolders = directoryContent.Where(c => c.Type == new StringEnum<ContentType>(ContentType.Dir));
	foreach (var subFolder in subFolders)
	{
		var filesInSubFolder = await GetFilesFromRepoAsync(context, addin, extensions, subFolder.Path).ConfigureAwait(false);
		files.AddRange(filesInSubFolder);
	}

	return files.ToArray();
}
```

This way of searching for files with a given extension generates a lot of API calls if a given repo contains a lot of folders and sub-folders.

**Comment by AdmiringWorm** [comment]
Yeah, that would certainly hit the abuse rate limit quite fast.

I see two options here though.
1. Download the source archive and check it for the needed files manually (example archive url: https://github.com/cake-contrib/Cake.Transifex/archive/develop.zip)
2. Use the `trees` api endpoint to get all files in the repository (example end point https://api.github.com/repos/cake-contrib/Cake.Transifex/git/trees/develop?recursive=1), this would require to know the default branch though, and I haven't checked if octokit.net implements this endpoint ([api endpoint docs](https://developer.github.com/v3/git/trees/#get-a-tree-recursively)

**Comment by Jericho** [comment]
Funny’s your archive suggestion is exactly what I ended up implementing last night before going to bed and I was surprised how quick it is. For my own education i will research your second suggestion. 

At this point though, I’m satisfied and I was able to run the discoverer to completion on all addins. About 140 PRs submitted!
