### ISSUE TITLE
The SubmitGithubPullRequest step should ensure unit test project also reference the right version of Cake

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#48]
The current logic is to only process the csproj with a name that matches `$"{addin.Name}.csproj"` however I received feedback that some addin author reference Cake.Core and/or Cake.Common in their unit test projects. Therefore we should also process other csproj files.

- [x] Process all `csproj` files
- [x] If a `csproj` references `Cake.Testing`, it must be the latest version

**Comment by AdmiringWorm** [comment]
Don't forget about `Cake.Testing` in unit tests, this would also need to be updated together with `Cake.Core`/`Cake.Common`.

**Comment by Jericho** [comment]
oh. I didn't know about that. Is the version of Cake.Testing always in lock step with Cake.Core and Cake.Common?

**Comment by AdmiringWorm** [comment]
From what I can tell, yes it is. Whenever Cake.Core or Cake.Common gets bumped, so do Cake.Testing

**Comment by Jericho** [comment]
It just occurred to me: my logic currently enforces `PrivateAssets=All` in all csproj. This is only necessary in `{addin.Name".csproj}`.
