### ISSUE TITLE
YAML synchronization improvements

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#52]
A long discussion with several comments followed the latest PR submitted by the AddinDiscoverer. I want to collect them here so I can implement them in the next release

**Improvement 1**
The format of the repository URL should be standardized. Some URLs have a slash at the end and some don't. Like the following example:
`https://github.com/agc93/Cake.AutoRest` 
`https://github.com/agc93/Cake.AutoRest/`

What is our preference?

(personally I prefer without the trailing slash)

**Comment by Jericho** [comment]
**Improvement 2**
What should we do with `prerelease` addin versions? Currently they are processed like any other addin version, including updating the content of their YAML file on the cake website. What should we do with prerelease version?

Continue processing them like we currently do?
Completely exclude them from automated audit?
Process them an include them in the generated audit report but exclude them from YAML synchronization?

**Comment by AdmiringWorm** [comment]
> What should we do with prerelease packages?

I would say it depends.
If it is released as a pre-release package on nuget, then I would say ignore it.
If it is marked as pre-release on github, but released as stable, then include it as normal.

Thit is just my opinion though of course.

**Comment by gep13** [comment]
As far as the first improvement is concerned, I also would suggest that no slash at the end would be the way to go.

For the second, the more I think about it, the more I think we just shouldn't have that prerelease tag in the yml file at all.  Looking at the main [addins page](https://cakebuild.net/addins/) there is no mention of it at all, which is where I would expect to see it.  If it is being used elsewhere on the site, I can't immediately find it.

@devlead @daveaglick @patriksvensson @pascalberger @mholo65 @agc93 what are your thoughts on this?

**Comment by Jericho** [comment]
The prerelease value in YAML file is used by Wyam in order to be able to download the package and its dependencies and to generate its documentation so I don't think we can avoid including it in the content (@daveaglick feel free to correct me if I'm wrong).

**Comment by Jericho** [comment]
Improvement number 1 will be tracked in #71.

**Comment by agc93** [comment]
As an avid user of the prerelease tag, my personal opinion is definitely to just ignore/skip packages with prerelease since they might not be stable, *especially* when a stable package with the same ID exists.

**Comment by gep13** [comment]
I guess the main question that has to be answered here, and perhaps @Jericho has already answered it, is what is the prerelease tag used for.  Historically, these yml files were not updated very often, if at all, so what exact purpose does it serve? If we can answer that, then I think we can make a plan going forward.

**Comment by Jericho** [comment]
@gep13 It is my understanding the this `Prerelease` value in the yaml file is used by Wyam when fetching nuget packages and their dependencies. From experience I know that you have to specify whether you want to include or exclude prerelease packages when you use the nuget API so I'm assuming that's why Wyam needs this value.

This discussion is quickly focusing on the `Prerelease` value in YAML files but I also want to make sure we discuss whether we should audit prerelease packages in the first place.

**Comment by daveaglick** [comment]
That's correct - though it's not so much that Wyam needed the flag as Cake did to ensure we were downloading a prerelease package if that's what's needed. But it looks like that was changed a few months ago and the prerelease flag was deprecated in favor of a different mechanism: https://github.com/cake-build/website/commit/0e650574283129640e55ac0ae96dd156eaf1fddf#diff-4d3634747586b964df9f7712bc3ec669L155

@devlead can you confirm that the new package download logic doesn't rely on the prerelease flag? If so then we can probably remove it entirely from the addin specs (unless we want to action such addins in a different way like skipping them as @agc93 suggests).

**Comment by gep13** [comment]
>@Jericho said...
This discussion is quickly focusing on the Prerelease value in YAML files but I also want to make sure we discuss whether we should audit prerelease packages in the first place.

But I think the two are intrinsically linked.  The point that I was trying to make was not regarding the technicality of "why" the pre-release flag was there, but rather "how" it was being used.  Let me try to explain...

If we are not showing on the site, which I don't think we are, the fact that the addin which has been included, and potentially the documentation that it adds to the site, is coming form a pre-release package, then I don't really see the benefit in it being used currently.

If we are only downloading/consuming the latest (released) package version, which I think is the correct thing to do, then I don't think we would need the pre-release flag, and also, I don't think we should audit pre-release addin versions.

The only time that I would see that we would want to do this would be when an addin is first being created, and it has been released as a beta, and would want to be included in the site/audit.  After that stage is complete, and a released version has gone out, I would argue that we should only include the latest released version, unless we are making it VERY clear across the site, that what we are showing is some pre-release documentation.

Does that make sense?

**Comment by devlead** [comment]
@daveaglick prerelease flag was required by nuget.exe, now we fetch latest version from nuget API - likely regardless of pre-release or not. Perhaps we could add assembly version somewhere in doc generation so it's clear what's documented?

**Comment by daveaglick** [comment]
> Perhaps we could add assembly version somewhere in doc generation so it's clear what's documented?

That's an excellent idea - opened issue https://github.com/cake-build/website/issues/686

**Comment by agc93** [comment]
> we fetch latest version from nuget API - likely regardless of pre-release or not.

Is this something we can control? For addins that have a stable version and a prerelease version (at least using mine as an example), we shouldn't be generating docs from unstable/prerelease versions with potential breaking changes.

**Comment by devlead** [comment]
> 
> 
> > we fetch latest version from nuget API - likely regardless of pre-release or not.
> 
> Is this something we can control? For addins that have a stable version and a prerelease version (at least using mine as an example), we shouldn't be generating docs from unstable/prerelease versions with potential breaking changes.

Yes we would just need to change logic here
https://github.com/cake-build/website/blob/726566df8ee5b4770850881db43669b3561d78ae/nuget.cake#L38

**Comment by Jericho** [comment]
This has finally been addressed by #141 

Thanks @pascalberger !
