### ISSUE TITLE
Question about license detection

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AddinDiscoverer#66]
Can I ask how the license detection currently works?  If you look at the following:

![image](https://user-images.githubusercontent.com/1271146/62600106-f17c7d80-b8e5-11e9-922d-559c9246b863.png)

It would suggest that Cake.AppCenter, Cake.Dart and Cake.Flutter don't have licenses, but each of them do, and they are under the MIT license.

Any thoughts on why these aren't being picked up?

**Comment by Jericho** [comment]
The following text in the [generated markdown report](https://github.com/cake-contrib/Home/blob/master/Audit.md) attempts to explain where the license information comes from:

> The License column indicates the license selected by the addin author. PLEASE NOTE: this information is only available if the nuget package includes the new license metadata information (documented here and here) as opposed to the obsolete licenseUrl.

Looking at Cake.AppCenter's published nuspec, I see that it contains the following line:
```
<licenseUrl>https://raw.githubusercontent.com/cake-contrib/Cake.AppCenter/master/LICENSE</licenseUrl>
```
which is the old and obsolete license information and not the new license information that AddinDiscoverer is looking for. This explains why it shows as not having a license in the report.

I also see that you [updated the nuspec](https://github.com/cake-contrib/Cake.AppCenter/pull/8/files#diff-28a73f12cea16c25c18901b0981a20a4) in the github repo about 3 hours ago and you changed the license information to the new format. I am presuming that you will use this updated nuspec when you pack your project and it will become publicly available when you publish a new version of this addin. AddinDiscoverer will pickup this new information when it runs a few hour later.

I didn't look at the other two addins you mentioned but I imagine it's a similar situation.

**Comment by gep13** [comment]
@Jericho ok, perfect, this makes sense.  Thank you!
