### ISSUE TITLE
Include what version of NuGet package was used to generate audit report

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AddinDiscoverer#67]
I think this would be a good addition to the spreadsheet.  The reason that this came up, was due to this:

![image](https://user-images.githubusercontent.com/1271146/62826227-c2992c80-bbaf-11e9-9d5e-bc9b65be1474.png)

This is the latest report that is generated at the time of creating this issue, and currently the newest version of the Cake.Dart package is here:

![image](https://user-images.githubusercontent.com/1271146/62826239-e492af00-bbaf-11e9-8b6c-7de62063f1ce.png)

Which seems to be using the correct iconUrl.  It would be good to know if the generated report is just "mistaken" or whether it was generated on an older version of the NuGet package compared to what is released.

@Jericho what do you think?

**Comment by Jericho** [comment]
I assumed this report would always be "current" enough since it's generated twice a day but I see your point.

I can not only add a column called "Nuget Package version" but I can also make the content a hyperlink to nuget.org

**Comment by gep13** [comment]
>@Jericho said...
I can not only add a column called "Nuget Package version" but I can also make the content a hyperlink to nuget.org

That sounds great!

Should I raise another issue regarding the iconUrl for that package appearing as incorrect in the report?

**Comment by Jericho** [comment]
Correct me if I misunderstand the situation but I don't think there's any problem. The report was generated about 10 hours ago but the package was published 2 hours ago. Therefore the new version of the package will be picked when the next report will be generate roughly two hours from now. Am I not understanding the situation correctly?

**Comment by Jericho** [comment]
Here is the evidence showing AddinDiscoverer running 10 hours ago:
![image](https://user-images.githubusercontent.com/112710/62827084-32022280-bb96-11e9-8e5f-ce7a74fec680.png)

and the package published 2 hours ago:
![image](https://user-images.githubusercontent.com/112710/62827078-172fae00-bb96-11e9-8f8f-06ea0da39776.png)

**Comment by gep13** [comment]
@Jericho apologies.  I got confused as I didn't change the IconUrl, and I had assumed that it was already released with package version 0.2.0.  Looks like that wasn't the case:

https://github.com/cake-contrib/Cake.Dart/commit/d570fb7a51f66f85be6b002910f60245b0f37cf6#diff-3610566ca6ba8f92f2bc07942a9ad857

It has only been released in version 0.2.1, and not the Audit report is reflecting that correctly.

**Comment by Jericho** [comment]
Done

**Comment by gep13** [comment]
Sweet! 😄 Thank you for doing this!
