### ISSUE TITLE
Categories should be lower case in YAML file

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#69]
In order to prevent duplicate categories due to mixed casing, we will standardize on lowercase.

**Comment by gep13** [comment]
@Jericho thanks for doing this!

**Comment by Jericho** [comment]
While we are on the topic of standardizing the content of generated YAML files, can you weight in on [this discussion](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/52).
