### ISSUE TITLE
Additional check: does the addin exist under the cake-contrib organisation

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#7]
This should be reported but not recommend since it's not mandatory

**Comment by Jericho** [comment]
Assumption: an addin has been moved to the cake-contrib org if the repo owner is `cake-contrib`.

@gep13 do you agre with my assumption?

**Comment by gep13** [comment]
@Jericho where does the information about `repo owner` come from?

**Comment by Jericho** [comment]
It's derived from the github repo URL (e.g.: `http://github.com/<owner>/<repo_name>`) which itself comes from the `Repository` field in the yml file. If the repo URL is not provided, the fallback is to search the HTML source of the nuget package for an anchor with the following attribute: `data-track=outbound-project-url`

**Comment by gep13** [comment]
@Jericho relying on the `Project Site` is prone to human error as well.  Can you create another issue on the Home repo to go through and ensure that all Project Site URL's in the nuspec/csproj file of projects in the cake-contrib organisation point to the correct location?

**Comment by Jericho** [comment]
what would be the logic to determine if the `Project Site` is correct or not?

Please note that the audit tool already reports an error if the `Project Site` is empty like so: 
![image](https://user-images.githubusercontent.com/112710/39950017-9d094902-554c-11e8-8b81-0084d3d76a17.png)

**Comment by gep13** [comment]
I guess, the only way to ensure that things were correct would be to query for all the repositories that live in the cake-contrib organisation (this can be done using Octokit).  That way, we know what is in the org, and this could then be compared against what is said in the yaml file, or the nuspec file.

**Comment by Jericho** [comment]
See #14
