### ISSUE TITLE
Framework for Cake.Grunt is blank in the Excel report

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#72]

**Comment by Jericho** [comment]
What I am observing is that the `GetSupportedFrameworks()` method in `NuGet.Packaging.PackageReaderBase` which is supposed to return an enumeration of frameworks supported by a nuget package returns an empty enumeration in the case of Cake.Grunt. That explains why AddinDiscoverer displays a null value in the "Framework" column for this addin.

Now the question is: why is this method returning an empty enumaration in the first place?

**Comment by Jericho** [comment]
I don't know if this is the source of the problem but just noticed something different about the Cake.Grunt package compared to other packages.

Notice the DLL is in a folder called `netstandard2.0` which is directly off the root:
![image](https://user-images.githubusercontent.com/112710/63440262-8363aa80-c3fd-11e9-9bfd-47761a88253a.png)

compare with another package picked at random:
![image](https://user-images.githubusercontent.com/112710/63440472-dccbd980-c3fd-11e9-8d81-942df062a8fd.png)

As you can see, the `netstandard2.0` folder is inside the `lib` folder.

**Comment by gep13** [comment]
Oh wow, that is a great find!

I suspect that this is exactly the problem!  I will push out a new version of that package tonight, to see if that corrects the problem.

Thanks for doing that investigation.

**Comment by Jericho** [comment]
This problem was resolved with the latest release of Cake.Grunt. The issue turned out to missing `files` section in the nuspec which was added [here](https://github.com/cake-contrib/Cake.Grunt/commit/b3e7e2d751a11d2e3e67a1517f80d3de97821c0c).
