### ISSUE TITLE
Submit YAML changes individually

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#74]
I am noticing that it currently take quite a while for the PRs submitted by AddinDiscoverer to be reviewed. Most of the time there is a legitimate reason for delaying the review but nonetheless it take a long time and in the mean time no other PRs are submitted.

Instead of submitting one single PR to add/update/delete a few YAML files, I think we should submit individual PRs which will allow cake team members to review each one individually and if one of those PRs cannot be merged, it can be left open and it will not impede the submission of other PRs.

**Comment by gep13** [comment]
@Jericho I think that this is a good idea!
