### ISSUE TITLE
Clean up git branches and forks

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#75]
1. Figure out if there is a way to detect if a given branch in a fork is associated with a PR that was merged or closed and if so, delete the branch since it is no longer necessary.
2. Figure out if there is a way to detect when a fork no longer has any associated branches and/or PRs and, if so, delete the fork.

I don't know if there are any limitation in github on the number of forks and/or branches but I think it might be wise to clean up.

Is that necessary?

**Comment by gep13** [comment]
>@Jericho said...
Is that necessary?

On my personal gep13 account, I think I have a fork of almost every addin out there, and no one has ever complained to me yet 😄

**Comment by Jericho** [comment]
ok then I won't waste my time.

**Comment by AdmiringWorm** [comment]
> On my personal gep13 account, I think I have a fork of almost every addin out there, and no one has ever complained to me yet

Well the only one that would complain about that would be you (when you some day do some spring cleaning of the forks you got 😄)

**Comment by gep13** [comment]
Ha ha! Too true!
