### ISSUE TITLE
Color code the Recipe column

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#90]

**Comment by Jericho** [comment]
- No background color if Recipe is not used
- Red if prerelease is used (no matter which version)
- Red if version < 1.0.0
- Yellow if version >= 1.0.0 AND version < latest
- Green if version == latest

**Comment by Jericho** [comment]
If prerelease is not requested and version is not pinned, we can assume the latest recipe is referenced and therefore the color should be green, right?

**Comment by Jericho** [comment]
Here's what it will look like:
![image](https://user-images.githubusercontent.com/112710/64199438-54672300-ce58-11e9-9599-6eea207b43c9.png)

**Comment by gep13** [comment]
>@Jericho said...
If prerelease is not requested and version is not pinned, we can assume the latest recipe is referenced and therefore the color should be green, right?

Hmm, interesting...

Yes, I think that should be fine, yes.

Looks really good to me!
