### ISSUE TITLE
Column in Excel report to track addins with embedded icon

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.AddinDiscoverer#93]
```
error NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl
```

**Comment by Jericho** [comment]
https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg

**Comment by gep13** [comment]
@Jericho I am wondering if this should actually be a separate column?  Or how were you planning on marking this column up?  What would the states of the column be?

**Comment by AdmiringWorm** [comment]
Also worth to mention, the iconUrl deprecation will be in nuget v5.3 (and most likely equivalent of the .NET Core utility).

When that happens, everyone still using icon url would be thrown an error when the try to push with the version supporting the icon element.

*NOTE: That is at least my understanding of the spec*

**Comment by Jericho** [comment]
@gep13 I was thinking something like this:
![image](https://user-images.githubusercontent.com/112710/64354638-d0cf4280-cfcd-11e9-90f2-0785ff8d9dea.png)

**Comment by Jericho** [comment]
I was also thinking that I could also check the content of the embedded icon and determine if the recommended icon is used.

**Comment by gep13** [comment]
>@Jericho said...
I was thinking something like this:

Is this still going to check the validity of the URL?

>@Jericho said...
I was also thinking that I could check the content of the embedded icon and determine if the recommended icon is used

If you can, that would be great!

**Comment by Jericho** [comment]
> Is this still going to check the validity of the URL?

Yes. Here's the logic for color coding:

- Red if no icon information at all
- Red if IconUrl == old_rawgit_url
- Yellow if IconUrl == jsDelivr_url
- Yellow if IconUrl == any_custom_url
- Yellow if icon is embedded but it's not the recommended icon
- Green if icon is embedded and it's the recommended icon

**Comment by gep13** [comment]
@Jericho sounds good to me!

**Comment by AdmiringWorm** [comment]
> Green if icon is embedded and it's the recommended icon

Unless someone is using nuget 5.3, or .NET Core 3.0 (neither which is available in stable state yet) this will be yellow for (almost?) everyone.

**Comment by Jericho** [comment]
Yes yellow for the time being but our focus should be on the red ones: with about a month left before rawgit goes dark, there are 40+ addins that still use the icon on their CDN. 

I did a quick test yesterday and was able to generate a package with embedded icon but it got stripped when I uploaded to NuGet.org so not only will this only work when addin authors have the right tools on their machines (or on their CI environment) but also we have to wait for this feature to go live on NuGet.org
