### ISSUE TITLE
Support nuget.org deprecation feature

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.AddinDiscoverer#96]
nuget.org now supports [deprecation of packages](https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/). AddinDiscoverer should check if an addin is deprecated on nuget.org additionally to its existing deprecation check.

**Comment by pascalberger** [comment]
If you need to test I've marked some of mine as deprecated (e.g. https://www.nuget.org/packages/Cake.CodeAnalysisReporting/)

**Comment by Jericho** [comment]
Totally agree: we should support this feature.
