### ISSUE TITLE
Problem with newlines in yml files

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.AddinDiscoverer#99]
I ran into an issue when trying to merge this PR:

https://github.com/cake-build/website/pull/755

There were newlines in the yml file for the description attribute, and this was causing problems during the parsing.  I don't know if this is an issue with the parsing that is happening on the website, or with the yml generation, but I thought I would raise the issue here to start with.

**Comment by Jericho** [comment]
I’m guessing this means that the description must be quoted if it contains a new line???

**Comment by gep13** [comment]
@Jericho It seems like it should be possible:

https://yaml-multiline.info/

I tried one suggestion, which was to use | but that didn't work, so I removed all the newlines in the description, and this worked, but I suspect that the next run of Cake.AddinDiscoverer will attempt to change it again?

**Comment by Jericho** [comment]
Yes AddinDisco will notice the descrepency and will submit a PR. Let's not accept the PR until we figure out the desired syntax.

**Comment by Jericho** [comment]
I take back my last comment. I reviewed the "YAML synchronization" logic and AddinDisco will **NOT** generate a PR to update the description for reasons [described here](https://github.com/cake-contrib/Cake.AddinDiscoverer/issues/50).

**Comment by Jericho** [comment]
Seems [using double quotes](https://github.com/cake-build/website/pull/774/commits/75bbfeee0aeb8a5bce32d30acd4ae6c851e52849) solves the problem. Here's the successful build: https://ci.appveyor.com/project/cakebuild/website/builds/28098605#L373

**Comment by gep13** [comment]
@Jericho thanks for investigating this!  Is this now "live"?  Should we merge that PR?
